# Generated by Django 5.2.7 on 2025-10-16 09:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_tags_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='services/banner/')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('canonical', models.URLField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=200, null=True)),
                ('og_description', models.CharField(blank=True, max_length=250, null=True)),
                ('og_type', models.CharField(default='website', max_length=50)),
                ('og_url', models.URLField(blank=True, max_length=500, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='services/og/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='canonical',
            field=models.CharField(default='https://compassionatecareadvisors.com/blogs/', max_length=900),
        ),
    ]
